version: '3'

services:
  api:
    image: exampleblogapi
    build:
      context: .
      dockerfile: ExampleBlogApi/Dockerfile
    ports:
      - "${APP_HTTP_PORT:-8080}:8080"
      - "${APP_HTTPS_PORT:-8081}:8081"
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
