version: '3'

services:
    api:
        image: exampleblogapi
        build:
            context: .
            dockerfile: ExampleBlogApi/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:${APP_HTTPS_PORT:-443};http://+:${APP_HTTP_PORT:-80}
        ports:
            - "${APP_HTTP_PORT:-80}:${APP_HTTP_PORT:-80}"
            - "${APP_HTTPS_PORT:-443}:${APP_HTTPS_PORT:-443}"
        networks:
            - app-network

    postgres:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_DB_PORT:-5432}:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    postgres-data:

networks:
    app-network:
